# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - docker build --tag rasee-redsquados:latest .
      - docker run --volume ./distro-iso:/home/kali/__WORKSHOP/devarmory/live-build-config/images rasee-redsquados:latest
    silent: true
